# Generated by Django 5.2.9 on 2026-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Radiology Staff'), ('receptionist', 'Receptionist'), ('doctor', 'Referral Doctor')], default='patient', max_length=20),
        ),
    ]
