# Generated by Django 6.0.1 on 2026-01-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='radiologist',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportaccess',
            name='accessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportaccess',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='reports.report'),
        ),
    ]
