# Generated by Django 5.2.9 on 2026-02-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_receptionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_description',
            field=models.CharField(blank=True, help_text='Brief description of appointment reason', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.scantype'),
        ),
    ]
