# Generated by Django 5.2.9 on 2026-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_patient_email_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_allergies',
            field=models.TextField(blank=True, default='', help_text='Any allergies the patient has'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_medical_conditions',
            field=models.TextField(blank=True, default='', help_text='Existing medical conditions or diseases'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
