# Generated by Django 5.2.9 on 2026-02-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_date_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_allergies',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_medical_conditions',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any allergies the patient reports'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='other_conditions',
            field=models.TextField(blank=True, help_text='Other diseases or medical conditions'),
        ),
    ]
